name: Pull Request Labeler

on:
  workflow_dispatch:
  pull_request_target:

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/labeler@v5
